package app.smdash

import android.content.Context

/** UI + patcher-log strings in English (default) and Russian, toggled in MainActivity. */
data class Strings(
    val installPatch: String,
    val removePatch: String,
    val startOverlay: String,
    val stopOverlay: String,
    val tunePositions: String,
    val dashSettings: String,
    // transparency settings panel
    val transpTitle: String,
    val transpHint: String,
    val transpLabel: String,
    val transpAuto: String,
    val close: String,
    val previewNote: String,
    // dashboard style picker
    val styleTitle: String,
    val styleArc: String,
    val styleStack: String,
    val styleStackTemp: String,
    val styleStrip: String,
    val styleMini: String,
    val styleAnalog: String,
    val analogNumTitle: String,
    val analogNumLabel: String,
    // patcher progress (some are prefixes the patcher appends a value to)
    val connecting: String,
    val noRootPrefix: String,
    val rootOk: String,
    val unpacking: String,
    val uploading: String,
    val applying: String,
    val mountFailed: String,
    val busy: String,
    val notFound: String,
    // shown when the stock Screenmate version isn't the one the patch is built for. The patcher
    // Composed as: prefix + <required> + mid + <found> + suffix — the versions are interpolated, never
    // hardcoded, so these survive every re-base. Two directions: OLD = the box is BEHIND (update
    // Screenmate, and the suffix says exactly how); NEW = the box is AHEAD (update SM Dash).
    val wrongStockOldPrefix: String,
    val wrongStockOldMid: String,
    val wrongStockOldSuffix: String,
    val wrongStockNewPrefix: String,
    val wrongStockNewMid: String,
    val wrongStockNewSuffix: String,
    val corrupt: String,
    val alreadyActive: String,
    val done: String,
    val errorPrefix: String,
    val revertConnecting: String,
    val revertNoRoot: String,
    val removingMounts: String,
    val layerRemains: String,
    val revertedPrefix: String,
    // hard reset (reload both dashboards + the settings menu from memory)
    val hardReset: String,
    val hardResetting: String,
    val hardResetDone: String,
    // in-app update card — the ONLY update surface that survives a Screenmate update, because the
    // injected settings panel disappears together with the patch
    val updTitle: String,
    val updCheck: String,
    val updChecking: String,
    val updCurrent: String,
    val updAvailPrefix: String,
    val updNeedStockPrefix: String,
    val updStockGonePrefix: String,
    val updFailed: String,
) {
    companion object {
        fun of(ru: Boolean): Strings = if (ru) RU else EN

        /** Persisted language choice (default English). */
        fun isRu(ctx: Context): Boolean =
            ctx.getSharedPreferences("ui", Context.MODE_PRIVATE).getBoolean("ru", false)

        fun setRu(ctx: Context, ru: Boolean) =
            ctx.getSharedPreferences("ui", Context.MODE_PRIVATE).edit().putBoolean("ru", ru).apply()

        val EN = Strings(
            installPatch = "🔧  Install patch (backup + autostart)",
            removePatch = "⟲  Remove patch (restore stock)",
            startOverlay = "▶  Start overlay",
            stopOverlay = "■  Stop overlay",
            tunePositions = "⚙  Tune positions",
            dashSettings = "◧  Dashboard style & transparency",
            transpTitle = "Dashboard transparency",
            transpHint = "Drag to fade our dashboard's background. “Auto” follows the car's own setting.",
            transpLabel = "Transparency",
            transpAuto = "Auto (car)",
            close = "Close",
            previewNote = "Preview — light backdrop simulates the bright screen behind the dashboard",
            styleTitle = "Dashboard style",
            styleArc = "Arc",
            styleStack = "Stack",
            styleStackTemp = "Temp",
            styleStrip = "Strip",
            styleMini = "Mini",
            styleAnalog = "Analog",
            analogNumTitle = "Analog — number position",
            analogNumLabel = "Numbers (radial)",
            connecting = "Connecting to local adbd (127.0.0.1:5555)…",
            noRootPrefix = "✗ No root via adbd: ",
            rootOk = "✓ root acquired",
            unpacking = "Unpacking patched stock…",
            uploading = "Uploading to device (~28 MB)…",
            applying = "Applying patch (bind-mount)…",
            mountFailed = "✗ Mount didn't apply",
            busy = "⏳ Busy — a patch operation is already running.",
            notFound = "✗ Screenmate stock dashboard not found — nothing to patch on this device.",
            wrongStockOldPrefix = "✗ This patch needs Screenmate ",
            wrongStockOldMid = ", but this box has ",
            wrongStockOldSuffix = ". Screenmate usually updates itself in the background — leave the box online for a " +
                "while and check again. If it stays behind, open the \"Updater\" app on the box, install any pending " +
                "update and reboot (some Screenmate versions arrive with the box firmware). Then tap Install patch again.",
            wrongStockNewPrefix = "✗ This patch is built for Screenmate ",
            wrongStockNewMid = ", but this box already has ",
            wrongStockNewSuffix = " — a newer stock. Update SM Dash: open the SM DASH panel in Screenmate settings " +
                "and use the update button there, or download the latest release from GitHub.",
            corrupt = "✗ Patch file integrity check failed — aborted, nothing changed.",
            alreadyActive = "✓ Patch already active — re-checked everything, all good.",
            done = "✓ Done — patch active",
            errorPrefix = "✗ Error: ",
            revertConnecting = "Connecting to adbd…",
            revertNoRoot = "✗ no root",
            removingMounts = "Removing bind-mount(s)…",
            layerRemains = "✗ a patch layer remains — try again",
            revertedPrefix = "✓ Patch removed (stock restored). Backup: ",
            hardReset = "⟳  Hard reset (reload dashboard + menu)",
            hardResetting = "Hard reset — unloading & reloading dashboard + menu…",
            hardResetDone = "✓ Reloaded — dashboard + menu restarted from memory",
            updTitle = "Updates",
            updCheck = "Check for updates",
            updChecking = "Checking…",
            updCurrent = "✓ Up to date",
            updAvailPrefix = "⤓  Update to v",
            updNeedStockPrefix = "Needs Screenmate ",
            updStockGonePrefix = "⚠ Screenmate updated — this build is for ",
            updFailed = "Couldn't reach GitHub — check the connection and retry",
        )

        val RU = Strings(
            installPatch = "🔧  Установить патч (бэкап + автозагрузка)",
            removePatch = "⟲  Снять патч (вернуть сток)",
            startOverlay = "▶  Запустить оверлей",
            stopOverlay = "■  Остановить оверлей",
            tunePositions = "⚙  Настройка позиций",
            dashSettings = "◧  Стиль и прозрачность дашборда",
            transpTitle = "Прозрачность дашборда",
            transpHint = "Тяни, чтобы сделать фон нашего дашборда прозрачнее. «Авто» — берёт настройку из машины.",
            transpLabel = "Прозрачность",
            transpAuto = "Авто (из машины)",
            close = "Закрыть",
            previewNote = "Превью — светлый фон имитирует яркий экран за дашбордом",
            styleTitle = "Стиль дашборда",
            styleArc = "Дуга",
            styleStack = "Стек",
            styleStackTemp = "Темп.",
            styleStrip = "Полоса",
            styleMini = "Мини",
            styleAnalog = "Аналог",
            analogNumTitle = "Аналог — положение цифр",
            analogNumLabel = "Цифры (радиально)",
            connecting = "Подключаюсь к локальному adbd (127.0.0.1:5555)…",
            noRootPrefix = "✗ Нет root через adbd: ",
            rootOk = "✓ root получен",
            unpacking = "Распаковываю пропатченный сток…",
            uploading = "Загружаю на устройство (≈28 МБ)…",
            applying = "Накладываю патч (bind-mount)…",
            mountFailed = "✗ Маунт не применился",
            busy = "⏳ Занято — операция уже выполняется.",
            notFound = "✗ Стоковый дашборд Screenmate не найден — на этом устройстве патчить нечего.",
            wrongStockOldPrefix = "✗ Патчу нужен Screenmate ",
            wrongStockOldMid = ", а на боксе ",
            wrongStockOldSuffix = ". Обычно Screenmate обновляется сам в фоне — дайте боксу побыть в сети и проверьте снова. " +
                "Если версия не растёт, откройте на боксе приложение «Updater», установите обновление и перезагрузитесь " +
                "(часть версий Screenmate приезжает вместе с прошивкой). Потом снова нажмите Install patch.",
            wrongStockNewPrefix = "✗ Патч собран под Screenmate ",
            wrongStockNewMid = ", а на боксе уже ",
            wrongStockNewSuffix = " — более новый сток. Обновите SM Dash: откройте панель SM DASH в настройках " +
                "Screenmate и нажмите кнопку обновления, либо скачайте свежий релиз с GitHub.",
            corrupt = "✗ Проверка целостности патча не прошла — отменено, ничего не изменено.",
            alreadyActive = "✓ Патч уже активен — всё перепроверено, порядок.",
            done = "✓ Готово — патч активен",
            errorPrefix = "✗ Ошибка: ",
            revertConnecting = "Подключаюсь к adbd…",
            revertNoRoot = "✗ нет root",
            removingMounts = "Снимаю bind-mount(ы)…",
            layerRemains = "✗ остался слой патча — попробуй ещё раз",
            revertedPrefix = "✓ Патч снят (сток восстановлен). Бэкап: ",
            hardReset = "⟳  Полный сброс (перезагрузить дашборд + меню)",
            hardResetting = "Полный сброс — выгружаю и перезагружаю дашборд + меню…",
            hardResetDone = "✓ Перезагружено — дашборд и меню перезапущены из памяти",
            updTitle = "Обновления",
            updCheck = "Проверить обновления",
            updChecking = "Проверяю…",
            updCurrent = "✓ Установлена последняя версия",
            updAvailPrefix = "⤓  Обновить до v",
            updNeedStockPrefix = "Требуется Screenmate ",
            updStockGonePrefix = "⚠ Screenmate обновился — эта сборка под ",
            updFailed = "Не достучался до GitHub — проверь связь и повтори",
        )
    }
}
